import './scss/main.scss';
import './js/booking-tickets.js';
import './js/gallery.js';
import './js/explore-filter.js';
import './js/header-nav.js';
import './js/active-slider.js';
import './js/video.js';
import './js/tickets.js';
import './js/mapbox.js';
